### ISSUE TITLE
Eclipse v16?

### ISSUE THREAD

**Issue by Shea1986** [VarianAPIs/PyESAPI#22]
Hi, does it work for Eclipse version 16? Thank you!

**Comment by mvarsta** [comment]
Hello !

Yes

From: Shea ***@***.***>
Sent: Monday, February 28, 2022 11:59
To: VarianAPIs/PyESAPI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VarianAPIs/PyESAPI] Eclipse v16? (Issue #22)


Hi, does it work for Eclipse version 16? Thank you!

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVarianAPIs%2FPyESAPI%2Fissues%2F22&data=04%7C01%7Cmarkus.varsta%40varian.com%7Cf3c51425aca24fdaa7a008d9fadba80c%7Cc49d9c494b114ccdb13772f88c68a252%7C1%7C0%7C637816643600904520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z2eHNOTosgVLNWlTelcPlvVvOuqiqojbkTNPxMH7hCM%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABNWD6DWITU5ZABDBZRSW5DU5OSWJANCNFSM5PRUJFRQ&data=04%7C01%7Cmarkus.varsta%40varian.com%7Cf3c51425aca24fdaa7a008d9fadba80c%7Cc49d9c494b114ccdb13772f88c68a252%7C1%7C0%7C637816643600904520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GfthbsdD%2FHwGrzG%2Bpt%2FuyIq086Tt62gjdODiLeflYCc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmarkus.varsta%40varian.com%7Cf3c51425aca24fdaa7a008d9fadba80c%7Cc49d9c494b114ccdb13772f88c68a252%7C1%7C0%7C637816643600904520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X70Q6r7V3TVByI2IFe4Ula%2BPnnGAH4DcosU8eVPf0YE%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmarkus.varsta%40varian.com%7Cf3c51425aca24fdaa7a008d9fadba80c%7Cc49d9c494b114ccdb13772f88c68a252%7C1%7C0%7C637816643600904520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fb%2BSo912hxNc%2FS%2BdypH%2FksoSlW%2BSS%2BIpus7oAyUQicw%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>


Varian Confidential
