### ISSUE TITLE
Using PyESAPI to connect to a remote TBOX

### ISSUE THREAD

**Issue by p-j-smith** [VarianAPIs/PyESAPI#35]
Hi, thanks for making PyESAPI! Is it possible to install PyESAPI on my local machine and use it to query Eclipse running on a remote TBOX?

**Comment by fizxmike** [comment]
Unfortunately, no. It can only run on a system with a client installed. Since it's intended for research only, is should either be installed on a test box (TBOX) having a stand alone eclipse system, or one of our cloud-based virtual machines offered by the Varian Innovation Center.

I've heard of some people wrapping a web API around PyESAPI using Flask. I've tried it in C# and asp.net, but it takes a very specific configuration since ESAPI is very strict about single thread access.
