### ISSUE TITLE
Problem installing PyESAPI

### ISSUE THREAD

**Issue by MichaelLempart** [VarianAPIs/PyESAPI#8]
Hi.

Iam trying to install PyESAPI on one of our TBOXes, but without any success.
I wrote: 

https://raw.githubusercontent.com/VarianAPIs/PyESAPI/master/condaenv36.yml 

in the Anaconda prompt, which gives me a list of all the dependencies. 
But when I try to create the Environment with:

conda env create -f condaenv36.yml

I get the error: file condaenv36.yml not found.

I also tried to install PyESAPI using pip but here it seems like there is an issue with pythonnet. 

Any help would be appreciated!

Kind regards,

Michael

**Comment by zackmorelli** [comment]
Hi Micheal,

I also struggled with this same problem for a while.  You need to copy and paste the exact command from the instructions (curl -O https://raw.githubusercontent.com/VarianAPIs/PyESAPI/master/condaenv36.yml) into the Anaconda prompt. If it works peoperly, you should see your prompt doing a bunch of stuff to set up the PYESAPI environment. I think the problem is the "O" in curl -O is the LETTER O, not a zero.

**Comment by zackmorelli** [comment]
By the way, for all of this to work in a Citrix environment, does this need to be installed in the TBOX, and not on a local computer (which i did)?

**Comment by fizxmike** [comment]
Yes, PyESAPI must be installed on a TBOX (Eclipse Workstation). However, it is possible to host Jupiter notebook in a way that allows you to access from your local computer (but you'd need admin rights to adjust firewall, etc.).
